stages:
  - test

variables:
  GIT_STRATEGY: clone

test_job:
  stage: test
  script:
    - echo "Running tests..."
    - # Здесь можно добавить команды для запуска тестов
  only:
    - master
  except:
    - merge_requests

manual_test_job:
  stage: test
  script:
    - echo "Running manual tests..."
    - # Здесь можно добавить команды для запуска тестов вручную
  when: manual
  only:
    - merge_requests
