version: '3'

services:

  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: flask_db
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: secret

  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - database
