name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Django Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: mydatabase
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DJANGO_SECRET_KEY: your_secret_key_here
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      DB_HOST: localhost

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      

    - name: Verify installation
      run: |
        pip list
        
    - name: Run migrations
      run: |
        python manage.py migrate
      working-directory: homework_07/myproject 

    - name: Run tests
      run: |
        python manage.py test
      working-directory: homework_07/myproject 

    - name: Run tests with coverage (optional)
      run: |
        pip install coverage
        coverage run --source='.' manage.py test
        coverage report
        coverage xml
      working-directory: homework_07/myproject 


    - name: Upload coverage to Codecov (optional)
      uses: codecov/codecov-action@v3
      with:
        file: homework_07/myproject/coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}  # Ensure you have the token in your repository secrets
